name: Build and Deploy Jekyll GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Build Release Binaries
      run: make release
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
        
    - name: Create Gemfile
      run: |
        cat > Gemfile << 'EOF'
        source "https://rubygems.org"
        gem "jekyll", "~> 4.3.0"
        gem "minima", "~> 2.5"
        gem "jekyll-feed", "~> 0.12"
        gem "jekyll-sitemap", "~> 1.4"
        EOF
        
    - name: Install Jekyll dependencies
      run: bundle install
        
    - name: Build Jekyll site
      run: bundle exec jekyll build
      env:
        JEKYLL_ENV: production
        
    - name: Copy binaries to built site
      run: |
        mkdir -p _site/dist
        cp -r dist/* _site/dist/
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3

  deploy:
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
